import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[window]
opacity = 0.9
decorations = "None"
padding = { x = 10, y = 10 }
title = "chubbs hacking"
dynamic_title = false

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Medium" }
size = 13.0
